name: Cargo Test

on:
  push:
    branches: [main]
    paths-ignore:
      - ".gitignore"
      - "LICENSE-*"
      - "README.md"
  pull_request:
    branches: [main]
    paths-ignore:
      - ".gitignore"
      - "LICENSE-*"
      - "README.md"

jobs:
  test:
    name: "Test"
    strategy:
      matrix:
        os:
          - "windows-latest"
          - "ubuntu-latest"
          - "macos-latest"

    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install GNU tar for macos
        if: matrix.os == 'macos-latest'
        run: |
          brew install gnu-tar
          echo "/usr/local/opt/gnu-tar/libexec/gnubin" >> $GITHUB_PATH
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-test-${{ hashFiles('**/Cargo.lock') }}

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Run cargo test
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --all
